version: '3'
services: 
 
  db:
    image: postgres:13-alpine
    env_file: .env
    restart: unless-stopped
    networks:
      - backend
    ports: 
      - ${PG_PORT}:${PG_PORT}
    environment:
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../postgresData:/var/lib/postgresql/data 

networks:
  backend:
    driver: bridge